services:

  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=sophia'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=deamon'
